/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YouRouteImport } from './routes/you'
import { Route as SearchRouteImport } from './routes/search'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeirloomIndexRouteImport } from './routes/heirloom.index'
import { Route as EntryEntryIdRouteImport } from './routes/entry.$entryId'

const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeirloomIndexRoute = HeirloomIndexRouteImport.update({
  id: '/heirloom/',
  path: '/heirloom/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryEntryIdRoute = EntryEntryIdRouteImport.update({
  id: '/entry/$entryId',
  path: '/entry/$entryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/you': typeof YouRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/heirloom/': typeof HeirloomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/you': typeof YouRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/heirloom': typeof HeirloomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/search': typeof SearchRoute
  '/you': typeof YouRoute
  '/entry/$entryId': typeof EntryEntryIdRoute
  '/heirloom/': typeof HeirloomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/search'
    | '/you'
    | '/entry/$entryId'
    | '/heirloom/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/search' | '/you' | '/entry/$entryId' | '/heirloom'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/search'
    | '/you'
    | '/entry/$entryId'
    | '/heirloom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  SearchRoute: typeof SearchRoute
  YouRoute: typeof YouRoute
  EntryEntryIdRoute: typeof EntryEntryIdRoute
  HeirloomIndexRoute: typeof HeirloomIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heirloom/': {
      id: '/heirloom/'
      path: '/heirloom'
      fullPath: '/heirloom/'
      preLoaderRoute: typeof HeirloomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$entryId': {
      id: '/entry/$entryId'
      path: '/entry/$entryId'
      fullPath: '/entry/$entryId'
      preLoaderRoute: typeof EntryEntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  SearchRoute: SearchRoute,
  YouRoute: YouRoute,
  EntryEntryIdRoute: EntryEntryIdRoute,
  HeirloomIndexRoute: HeirloomIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
